version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: hackathon
      MYSQL_USER: uttc
      MYSQL_PASSWORD: 0120
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-container
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user_name
      MYSQL_PASSWORD: user_password
      MYSQL_HOST: mysql